apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: test-net-rhtap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-net-rhtap 
  name: test-net-rhtap
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-net-rhtap
    weight: 100 
